stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
    outs:
      - data/data_raw.csv
      - data/train.csv
      - data/test.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/train.csv
    outs:
      - models/model.pkl
    metrics:
      - train_metrics.json:
          cache: false

  validate:
    cmd: python validate.py
    deps:
      - validate.py
      - models/model.pkl
      - data/test.csv
    metrics:
      - test_metrics.json:
          cache: false
    plots:
      - confusion_matrix.png:
          cache: false
